# List of valid MessiScript words to use when assigning values.

CHANGE_SIGN = "fútbol"

NOUNS = [
    "actuación", "actuaciones",
    "astro", "astros",
    "banda", "bandas",
    "calidad", "calidades",
    "campo", "campos",
    "cancha", "canchas",
    "centro", "centros",
    "clase", "clases",
    "dios", "dioses",
    "estadio", "estadios",
    "estrella", "estrellas",
    "figura", "figuras",
    "galaxia", "galaxias",
    "gambeta", "gambetas",
    "habilidad", "habilidades",
    "ídola", "ídolo", "ídolos", "ídolos",
    "jugada", "jugadas",
    "jugador", "jugadora", "jugadores", "jugadoras",
    "lateral", "laterales",
    "leo", "lio", "leonel", "lionel",
    "muchacho", "muchachos", "muchacha", "muchachas",
    "mundo", "mundos",
    "país", "países",
    "partido", "partidos",
    "pelota", "pelotas",
    "pibe", "pibes", "piba", "pibas",
    "planeta", "planetas",
    "potencial", "potenciales",
    "pulga", "pulgas",
    "república", "repúblicas",
    "talento", "talentos",
    "titán", "titanes",
    "tribuna", "tribunas",
    "toda", "todo", "todas", "todos",
]

ADJECTIVES = [
    "argentina", "argentino", "argentinas", "argentinos",
    "favorita", "favorito", "favoritas", "favoritos",
    "fenomenal", "fenomenales",
    "futbolística", "futbolísticas", "futbolístico", "futbolísticos",
    "habilidosa", "habilidoso", "habilidosas", "habilidosos",
    "increible", "increibles",
    "irrepetible", "irrepetibles",
    "impecable", "impecables",
    "impresionante", "impresionantes",
    "magistral", "magistrales",
    "maravilloso", "maravillosa", "maravillosos", "maravillosas",
    "mundial", "mundiales",
    "nacional", "nacionales",
    "talentosa", "talentoso", "talentosas", "talentosos",
    "titánica", "titánico", "titánicas", "titánicos",
    "tremenda", "tremendo", "tremendas", "tremendos",
    "única", "único", "únicas", "únicos",
]
